DATA C2_2_paractice ;
SET TRAINING.NPS200 (FIRSTOBS=21 OBS=50) ;
KEEP SPEC_ID_SNO JID RECU_FR_DD RECU_T0_DD ;
RUN;

PROC CONTENTS DATA=TRAINING.NPS200;
RUN;

PROC CONTENTS DATA=TRAINING.NPS200
ORDER = VARNUM;
RUN;

DATA C3_1_MALE;
SET TRAINING.NPS200;
IF SEX_TP_CD='1';
RUN;

DATA C3_1_FEMALE_GT60;
SET TRAINING.NPS200;
IF SEX_TP_CD='2' AND AGG IN ('13','14','15','16');
RUN;

DATA C3_1_FOM ; 
SET TRAINING.NPS200;
IF FOM_TP_CD = '021' THEN NEW_FOM_CD=1;
ELSE NEW_FOM_CD=2;
RUN;

DATA C3_2_RESP;
SET TRANING.NPS200;
IF SUBSTR(MSICK_CD,1,1)='J' THEN RESP_YN=1 ;
ELSE RESP_YN=0;
RUN;

DATA C3_2_RESP2;
SET TRANING.NPS200;
IF SUBSTR(SICK_CE,1,1)='J' AND SICK_SNO <=3 THEN RESP_YN =1;
ELSE RESP_YN=0;
RUN;

PROC SORT DATA = C2_2_PRACTICE OUT= C3_3_MERGE1;
BY SPEC_ID_SNO;
RUN;

PROC SORT DATA = TRAINING.NPS400 OUT= C3_3_MERGE2;
BY SPEC_ID_SNO;
RUN;

DATA C3_3_MERGE;
MERGE C3_3_MERGE1(IN=A) C3_3_MERGE2(IN=B);
BY SPEC_ID_SNO;
IF A;
RUN;

PROC SORT DATA = TRAINING.NPS200 
OUT=C3_4_NODUPKEY (KEEP=JID) NODUPKEY;
BY JID;
RUN;

PROC FREQ DATA=TRAINING.NPS200;
TABLES SEX_TP_CD INSUF_TF_CD;
TABLES SEX_TP_CE*INSUF_TF_CD;
RUN;


/*예제1*/
DATA C4_EX1;
SET TRAINING.NPS200;
IF SUBSTR(MSICK_CD,1,3) IN ('J45','J46') THEN ASTHMA=1;
ELSE ASTHMA = 0;
RUN;

DATA C4_EX2;
SET C4_EX1;
WHERE ASTHMA=1;
RUN;

PROC FREQ DATA=C4_EX2;
TABLES SEX_TP_CD;
RUN;


/*예제2*/
PROC FREQ DATA=C4_EX2;
TABLES SEX_TP_CD DGSBJT_CD SEX_TP_CD*DGSBJT_CD;
RUN;


/*예제3*/
DATA C4_EX3;
SET C4_EX1;
MON = MONTH(RECU_FR_DD);
WHERE ASTHMA=1;
RUN;

PROC FREQ DATA=C4_EX3;
TABLES MON*SEX_TP_CE*DGSBJT_CD;
RUN;

/*NPS200과 NPS_YK연결하기*/
PROC SQL;
CREATE TABLE NPS200_YK AS 
SELECT A.*,B.CL_CD
FROM TRAINING.NPS200 AS A
LEFT JOIN TRAINING.NPS_YK AS B
ON A.YID = B.YID;
QUIT;

/*NPS200에서 주상병 J00,J01 환자 수 카운트하기*/
PROC SQL;
CREATE TABLE C1_1_CNT1 AS
SELECT COUNT(DISTINCT JID) AS CNT_JID
FROM TRAINING.NPS200
WHERE SUBSTR(MSICK_CD,1,3) IN ('J00','J01');
QUIT;

/*상병순위 3순위까지 J00,J01 환자 수 카운트 하기*/
PROC SQL;
CREATE TABLE C1_1_CNT2 AS
SELECT COUNT(DISTINCT A.JID) AS CNT_JID
FROM TRAINIG.NPS200 AS A
LEFT JOIN TRAINING.NPS400 AS B
ON A.SPEC_ID_SNO=B.SPEC_ID_SNO
WHERE SUBSTR(B.SICK_CD,1,3) IN ('J00','J01') AND B.SICK_SNO<=3;
QUIT;

/*다빈도 주상병(3단)조회하기*/
PROC SQL;
CREATE TABLE C1_1_CNT3 AS
SELECT SUBSTR(MSICK_CD,1,3) AS DZ, 
              COUNT(DISTINCT JID) AS CNT_PAT
FROM TRAININIG.NPS200
GROUP BY DZ
ORDER BY CNT_PAT DESC;
QUIT;

/*의과 외래에서 감기(주상병)에 대한 종별 환자 수 카운트하기*/
PROC SQL;
CREATE TABLE C1_1_DZ AS
SELECT CL_CD, COUNT(DISTINCT JID) AS CNT_PAT
FROM NPS200_YK
WHERE SUBSTR(MSICK_CD,1,3) IN ('J00','J01','J02','J03','J04','J05','J06') AND FOM_TP_CD='031'
GROUP BY CL_CD;
QUIT;

/*의약품통계산출하기*/
PROC SQL;
CREATE TABLE C1_2_MED AS
SELECT A.JID,
             AVG(B.TOT_USE_QTY_OR_EXEC_FQ) AS AVG_USE,
			 SUM(B.AMT) AS TOT_AMT
FROM TRAINING.NPS200 AS A
LEFT JOIN TRAINING. NPS300 AS B
ON A.SPEC_ID_SNO=B.SPEC_ID_SNO
WHERE SUBSTR(A.MSICK_CD,1,3) IN ('J00','J01','J02','J03','J04','J05','J06')
            AND B.GNL_NM_CD='279601AT'
GROUP BY A.JID;
QUIT;

/*유방암 질병 진단 시 진료비 최소비용과 최대비용 산출하기*/
PROC SQL;
CREATE TABLE C1_1_TRT1 AS
SELECT MIN(A.RVD_RPE_TAMT_AMT+A.RVD_P100LT_TOT_AMT) AS MIN_AMT,
             MAX(A.RVD_RPE_TAMT_AMT+A.RVD_P100LT_TOT_AMT) AS MAX_AMT
FROM TRAINING.NPS200 AS A
LEFT JOIN TRAINING.NPS300 AS B
ON A.SPEC_ID_SNO = B.SPEC_ID_SNO
WHERE SUBSTR(A.MSICK_CD,1,3) IN ('C50','D05')
            AND SUBSTR(B.DIV_CD,1,2)='AA';
QUIT;

/*1-1*/
PROC SQL;
CREATE TABLE Q1_1 AS
SELECT A.AGG, SUM(A.RVD_RPE_TAMT_AMT) AS SUM_AMT
FROM TRANING.NPS200 AS A LEFT JOIN TARAININIG.NPS300 AS B
ON A.SPEC_ID_SNO=B.SPEC_ID_SNO
WHERE YEAR(A.RECU_FR_DD)=2015 AND A.INSUP_TP_CD='4' AND B.DIV_CE='KK010'
GROUP BY A.AGG;
QUIT;

/*1-2*/
PROC SQL;
CREATE TABLE Q1_2 AS
SELECT SUBSTR(A.MSICK_CD,1,3) AS JU, 
              COUNT(A.SPEC_ID_SNO) AS SPEC_CNT, 
              COUNT(DISTINCT A.JID) AS JID_CNT,
			  SUM(RVD_RPE_TAMT_AMT) AS SUM_AMT
FROM TRANING.NPS200 AS A LEFT JOIN TARAININIG.NPS300 AS B
ON A.SPEC_ID_SNO=B.SPEC_ID_SNO
WHERE YEAR(A.RECU_FR_DD)=2015 AND A.INSUP_TP_CD='4' AND B.DIV_CE='KK010'
GROUP BY JU;
QUIT;

/*2-1*/
PROC SQL;
CREATE TABLE Q2_1 AS
SELECT A.AGG,
             COUNT(A.SPEC_ID_SNO) AS SPEC_CNT,
			 SUM(B.AMT) AS SUM_AMT,
			 SUM(B.TOT_USE_QTY_OR_EXEC_FQ) AS SUM_USE
FROM TRANING.NPS200 AS A LEFT JOIN TRAINING.NPS300 AS B
ON A.SPEC_ID_SNO=B.SPEC_ID_SNO
WHERE YEAR(A.RECU_FR_DD)=2015 AND A.INSUP_TP_CD='4' AND GNL_NM_CD='279601AT'
GROUP BY A.AGG;
QUIT;

